"""Add try_count to the verifications table

Revision ID: 04bb63400551
Revises: 0dd595926818
Create Date: 2025-01-28 15:14:57.163057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04bb63400551"
down_revision: Union[str, None] = "0dd595926818"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.add_column("verifications", sa.Column("try_count", sa.Integer(), nullable=True))
    op.execute("UPDATE verifications SET try_count=0")
    op.alter_column("verifications", "try_count", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verifications", "try_count")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
