"""Add email confirmation boolean to User table

Revision ID: 0dd595926818
Revises: 
Create Date: 2025-01-18 13:58:34.205890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dd595926818"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_email_confirmed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.alter_column(
        "users",
        "is_admin",
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        existing_nullable=False,
        postgresql_using="is_admin::boolean",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_admin",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="is_admin::text",
    )
    op.drop_column("users", "is_email_confirmed")
    # ### end Alembic commands ###
